### ISSUE TITLE
[BUG] The bot won't run

### ISSUE THREAD

**Issue by Avenred** [SpencerComputers/Rainbot#4]

**Comment by spencermacca** [comment]
I'll start working on this, I believe it's just my retard code :P

**Comment by Avenred** [comment]
Sounds good! I guess your spaghetti code finally caught up to you...

**Comment by Avenred** [comment]
So I just now figured this out,
I was running my own fork of the bot which didn't work. Upon downloading the normal source code, it actually works.
Sorry about that!
(It seems my spaghetti code finally caught up to me...)
